Installing and importing Libraries

In [4]:
!pip install pandas
!pip install numpy

Requirement already satisfied: pandas in /Users/spol29/anaconda3/lib/python3.10/site-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/spol29/anaconda3/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/spol29/anaconda3/lib/python3.10/site-packages (from pandas) (2022.7)
Requirement already satisfied: numpy>=1.21.0 in /Users/spol29/anaconda3/lib/python3.10/site-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /Users/spol29/anaconda3/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Requirement already satisfied: numpy in /Users/spol29/anaconda3/lib/python3.10/site-packages (1.23.5)

In [5]:
import pandas as pd
import numpy as np

Input the CSV file

In [6]:
df = pd.read_csv("Solar.csv")
df

,Location,Date,Time,Latitude,Longitude,Altitude,YRMODAHRMI,Month,Hour,Season,Humidity,AmbientTemp,PolyPwr,Wind.Speed,Visibility,Pressure,Cloud.Ceiling
0,Camp Murray,20171203,1145,47.11,-122.57,84,2.017120e+11,12,11,Winter,81.71997,12.86919,2.42769,5,10.0,1010.6,722
1,Camp Murray,20171203,1315,47.11,-122.57,84,2.017120e+11,12,13,Winter,96.64917,9.66415,2.46273,0,10.0,1011.3,23
2,Camp Murray,20171203,1330,47.11,-122.57,84,2.017120e+11,12,13,Winter,93.61572,15.44983,4.46836,5,10.0,1011.6,32
3,Camp Murray,20171204,1230,47.11,-122.57,84,2.017120e+11,12,12,Winter,77.21558,10.36659,1.65364,5,2.0,1024.4,6
4,Camp Murray,20171204,1415,47.11,-122.57,84,2.017120e+11,12,14,Winter,54.80347,16.85471,6.57939,3,3.0,1023.7,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21040,USAFA,20180928,1530,38.95,-104.83,1947,2.018090e+11,9,15,Fall,11.66992,43.22510,9.79611,14,10.0,802.3,722
21041,USAFA,20180929,1300,38.95,-104.83,1947,2.018090e+11,9,13,Fall,18.22510,28.98247,10.88992,13,10.0,799.2,722
21042,USAFA,20180929,1400,38.95,-104.83,1947,2.018090e+11,9,14,Fall,15.52124,33.49167,8.24479,10,10.0,798.4,722
21043,USAFA,20180929,1500,38.95,-104.83,1947,2.018090e+11,9,15,Fall,6.63452,51.62163,12.47328,10,10.0,797.8,722
21044,USAFA,20181001,1400,38.95,-104.83,1947,2.018100e+11,10,14,Fall,22.58301,32.83958,6.39732,15,10.0,801.2,110

Data Wrangling

In [7]:
df.head(20)

,Location,Date,Time,Latitude,Longitude,Altitude,YRMODAHRMI,Month,Hour,Season,Humidity,AmbientTemp,PolyPwr,Wind.Speed,Visibility,Pressure,Cloud.Ceiling
0,Camp Murray,20171203,1145,47.11,-122.57,84,2.017120e+11,12,11,Winter,81.71997,12.86919,2.42769,5,10.0,1010.6,722
1,Camp Murray,20171203,1315,47.11,-122.57,84,2.017120e+11,12,13,Winter,96.64917,9.66415,2.46273,0,10.0,1011.3,23
2,Camp Murray,20171203,1330,47.11,-122.57,84,2.017120e+11,12,13,Winter,93.61572,15.44983,4.46836,5,10.0,1011.6,32
3,Camp Murray,20171204,1230,47.11,-122.57,84,2.017120e+11,12,12,Winter,77.21558,10.36659,1.65364,5,2.0,1024.4,6
4,Camp Murray,20171204,1415,47.11,-122.57,84,2.017120e+11,12,14,Winter,54.80347,16.85471,6.57939,3,3.0,1023.7,9
5,Camp Murray,20171204,1430,47.11,-122.57,84,2.017120e+11,12,14,Winter,47.10083,18.12363,2.92027,0,5.0,1023.7,722
6,Camp Murray,20171205,1115,47.11,-122.57,84,2.017120e+11,12,11,Winter,43.55469,19.41269,3.41284,0,4.0,1025.7,722
7,Camp Murray,20171205,1200,47.11,-122.57,84,2.017120e+11,12,12,Winter,30.56641,23.90930,4.82020,5,7.0,1026.0,722
8,Camp Murray,20171205,1300,47.11,-122.57,84,2.017120e+11,12,13,Winter,17.90771,32.32346,5.98127,5,10.0,1025.7,722
9,Camp Murray,20171205,1400,47.11,-122.57,84,2.017120e+11,12,14,Winter,14.40430,35.41267,4.96121,6,10.0,1025.4,722
10,Camp Murray,20171205,1500,47.11,-122.57,84,2.017120e+11,12,15,Winter,15.72876,32.91763,2.85006,6,10.0,1025.0,722
11,Camp Murray,20171206,1130,47.11,-122.57,84,2.017120e+11,12,11,Winter,26.18408,25.84541,4.67733,3,3.0,1025.7,722
12,Camp Murray,20171206,1200,47.11,-122.57,84,2.017120e+11,12,12,Winter,23.71216,27.76642,4.78501,0,5.0,1025.7,722
13,Camp Murray,20171206,1300,47.11,-122.57,84,2.017120e+11,12,13,Winter,15.93628,36.06476,6.19272,0,10.0,1025.4,722
14,Camp Murray,20171206,1400,47.11,-122.57,84,2.017120e+11,12,14,Winter,16.70532,34.82101,5.17233,3,10.0,1024.4,722
15,Camp Murray,20171206,1500,47.11,-122.57,84,2.017120e+11,12,15,Winter,13.39111,39.30000,3.09636,0,10.0,1023.7,722
16,Camp Murray,20171207,1200,47.11,-122.57,84,2.017120e+11,12,12,Winter,83.30078,8.36250,1.45144,0,0.3,1022.0,1
17,Camp Murray,20171207,1245,47.11,-122.57,84,2.017120e+11,12,12,Winter,82.89795,7.17163,2.46273,0,0.3,1022.0,2
18,Camp Murray,20171207,1300,47.11,-122.57,84,2.017120e+11,12,13,Winter,82.08618,7.72049,1.65364,0,0.3,1021.7,2
19,Camp Murray,20171207,1400,47.11,-122.57,84,2.017120e+11,12,14,Winter,72.70508,9.70192,1.75920,0,0.3,1021.3,2

In [8]:
num_rows, num_cols = df.shape
print(f"Rows: {num_rows}")
print(f"Columns: {num_cols}")

Rows: 21045
Columns: 17

In [9]:
#Describing Ranges
df.describe()

,Date,Time,Latitude,Longitude,Altitude,YRMODAHRMI,Month,Hour,Humidity,AmbientTemp,PolyPwr,Wind.Speed,Visibility,Pressure,Cloud.Ceiling
count,2.104500e+04,21045.000000,21045.000000,21045.000000,21045.000000,2.104500e+04,21045.000000,21045.000000,21045.000000,21045.000000,21045.000000,21045.000000,21045.000000,21045.000000,21045.000000
mean,2.017720e+07,1267.483725,38.213823,-108.593678,798.843668,2.017718e+11,6.565883,12.627845,37.121941,29.285117,12.978583,10.318318,9.700071,925.944747,515.966785
std,4.579585e+03,167.602767,6.323761,16.364130,770.681794,4.579846e+07,2.983958,1.672952,23.823011,12.366820,7.123255,6.385030,1.351949,85.215659,301.903379
min,2.017052e+07,1000.000000,20.890000,-156.440000,1.000000,2.017050e+11,1.000000,10.000000,0.000000,-19.981770,0.257330,0.000000,0.000000,781.700000,0.000000
25%,2.017111e+07,1100.000000,38.160000,-117.260000,2.000000,2.017110e+11,4.000000,11.000000,17.529300,21.915280,6.404570,6.000000,10.000000,845.500000,140.000000
50%,2.018032e+07,1300.000000,38.950000,-111.180000,458.000000,2.018030e+11,7.000000,13.000000,33.123780,30.289150,13.798700,9.000000,10.000000,961.100000,722.000000
75%,2.018062e+07,1400.000000,41.150000,-104.710000,1370.000000,2.018060e+11,9.000000,14.000000,52.593990,37.474670,18.863650,14.000000,10.000000,1008.900000,722.000000
max,2.018100e+07,1545.000000,47.520000,-80.110000,1947.000000,2.018100e+11,12.000000,15.000000,99.987790,65.738370,34.285020,49.000000,10.000000,1029.500000,722.000000

In [10]:
df.isnull().sum()

Location         0
Date             0
Time             0
Latitude         0
Longitude        0
Altitude         0
YRMODAHRMI       0
Month            0
Hour             0
Season           0
Humidity         0
AmbientTemp      0
PolyPwr          0
Wind.Speed       0
Visibility       0
Pressure         0
Cloud.Ceiling    0
dtype: int64

In [11]:
df.rename(columns={"Wind.Speed":"Wind_Speed"},inplace=True)
df

,Location,Date,Time,Latitude,Longitude,Altitude,YRMODAHRMI,Month,Hour,Season,Humidity,AmbientTemp,PolyPwr,Wind_Speed,Visibility,Pressure,Cloud.Ceiling
0,Camp Murray,20171203,1145,47.11,-122.57,84,2.017120e+11,12,11,Winter,81.71997,12.86919,2.42769,5,10.0,1010.6,722
1,Camp Murray,20171203,1315,47.11,-122.57,84,2.017120e+11,12,13,Winter,96.64917,9.66415,2.46273,0,10.0,1011.3,23
2,Camp Murray,20171203,1330,47.11,-122.57,84,2.017120e+11,12,13,Winter,93.61572,15.44983,4.46836,5,10.0,1011.6,32
3,Camp Murray,20171204,1230,47.11,-122.57,84,2.017120e+11,12,12,Winter,77.21558,10.36659,1.65364,5,2.0,1024.4,6
4,Camp Murray,20171204,1415,47.11,-122.57,84,2.017120e+11,12,14,Winter,54.80347,16.85471,6.57939,3,3.0,1023.7,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21040,USAFA,20180928,1530,38.95,-104.83,1947,2.018090e+11,9,15,Fall,11.66992,43.22510,9.79611,14,10.0,802.3,722
21041,USAFA,20180929,1300,38.95,-104.83,1947,2.018090e+11,9,13,Fall,18.22510,28.98247,10.88992,13,10.0,799.2,722
21042,USAFA,20180929,1400,38.95,-104.83,1947,2.018090e+11,9,14,Fall,15.52124,33.49167,8.24479,10,10.0,798.4,722
21043,USAFA,20180929,1500,38.95,-104.83,1947,2.018090e+11,9,15,Fall,6.63452,51.62163,12.47328,10,10.0,797.8,722
21044,USAFA,20181001,1400,38.95,-104.83,1947,2.018100e+11,10,14,Fall,22.58301,32.83958,6.39732,15,10.0,801.2,110

In [12]:
#Deleting a column
#df.drop('YRMODAHRMI', axis=1, inplace=True)
#df

In [13]:
df.groupby('Season')
df

,Location,Date,Time,Latitude,Longitude,Altitude,YRMODAHRMI,Month,Hour,Season,Humidity,AmbientTemp,PolyPwr,Wind_Speed,Visibility,Pressure,Cloud.Ceiling
0,Camp Murray,20171203,1145,47.11,-122.57,84,2.017120e+11,12,11,Winter,81.71997,12.86919,2.42769,5,10.0,1010.6,722
1,Camp Murray,20171203,1315,47.11,-122.57,84,2.017120e+11,12,13,Winter,96.64917,9.66415,2.46273,0,10.0,1011.3,23
2,Camp Murray,20171203,1330,47.11,-122.57,84,2.017120e+11,12,13,Winter,93.61572,15.44983,4.46836,5,10.0,1011.6,32
3,Camp Murray,20171204,1230,47.11,-122.57,84,2.017120e+11,12,12,Winter,77.21558,10.36659,1.65364,5,2.0,1024.4,6
4,Camp Murray,20171204,1415,47.11,-122.57,84,2.017120e+11,12,14,Winter,54.80347,16.85471,6.57939,3,3.0,1023.7,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21040,USAFA,20180928,1530,38.95,-104.83,1947,2.018090e+11,9,15,Fall,11.66992,43.22510,9.79611,14,10.0,802.3,722
21041,USAFA,20180929,1300,38.95,-104.83,1947,2.018090e+11,9,13,Fall,18.22510,28.98247,10.88992,13,10.0,799.2,722
21042,USAFA,20180929,1400,38.95,-104.83,1947,2.018090e+11,9,14,Fall,15.52124,33.49167,8.24479,10,10.0,798.4,722
21043,USAFA,20180929,1500,38.95,-104.83,1947,2.018090e+11,9,15,Fall,6.63452,51.62163,12.47328,10,10.0,797.8,722
21044,USAFA,20181001,1400,38.95,-104.83,1947,2.018100e+11,10,14,Fall,22.58301,32.83958,6.39732,15,10.0,801.2,110

In [30]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21045 entries, 0 to 21044
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       21045 non-null  object
 1   Date           21045 non-null  int64
 2   Time           21045 non-null  int64
 3   Latitude       21045 non-null  float64
 4   Longitude      21045 non-null  float64
 5   Altitude       21045 non-null  int64
 6   YRMODAHRMI     21045 non-null  float64
 7   Month          21045 non-null  float64
 8   Hour           21045 non-null  float64
 9   Season         21045 non-null  object
 10  Humidity       21045 non-null  float64
 11  AmbientTemp    21045 non-null  float64
 12  PolyPwr        21045 non-null  float64
 13  Wind_Speed     21045 non-null  float64
 14  Visibility     21045 non-null  float64
 15  Pressure       21045 non-null  float64
 16  Cloud.Ceiling  21045 non-null  float64
 17  Year           21045 non-null  float64
 18  Day            21045 non-null  float64
 19  Minute         21045 non-null  float64
dtypes: float64(15), int64(3), object(2)
memory usage: 3.2+ MB

,Date,Time,Latitude,Longitude,Altitude,YRMODAHRMI,Month,Hour,Humidity,AmbientTemp,PolyPwr,Wind_Speed,Visibility,Pressure,Cloud.Ceiling,Year,Day,Minute
count,2.104500e+04,21045.000000,21045.000000,21045.000000,21045.000000,2.104500e+04,21045.000000,21045.0,21045.000000,21045.000000,21045.000000,21045.000000,21045.000000,21045.000000,21045.000000,21045.000000,21045.0,21045.0
mean,2.017720e+07,1267.483725,38.213823,-108.593678,798.843668,2.017718e+11,6.565883,0.0,37.121941,29.285117,12.978583,10.318318,9.700071,925.944747,515.966785,2017.652411,0.0,0.0
std,4.579585e+03,167.602767,6.323761,16.364130,770.681794,4.579846e+07,2.983958,0.0,23.823011,12.366820,7.123255,6.385030,1.351949,85.215659,301.903379,0.476216,0.0,0.0
min,2.017052e+07,1000.000000,20.890000,-156.440000,1.000000,2.017050e+11,1.000000,0.0,0.000000,-19.981770,0.257330,0.000000,0.000000,781.700000,0.000000,2017.000000,0.0,0.0
25%,2.017111e+07,1100.000000,38.160000,-117.260000,2.000000,2.017110e+11,4.000000,0.0,17.529300,21.915280,6.404570,6.000000,10.000000,845.500000,140.000000,2017.000000,0.0,0.0
50%,2.018032e+07,1300.000000,38.950000,-111.180000,458.000000,2.018030e+11,7.000000,0.0,33.123780,30.289150,13.798700,9.000000,10.000000,961.100000,722.000000,2018.000000,0.0,0.0
75%,2.018062e+07,1400.000000,41.150000,-104.710000,1370.000000,2.018060e+11,9.000000,0.0,52.593990,37.474670,18.863650,14.000000,10.000000,1008.900000,722.000000,2018.000000,0.0,0.0
max,2.018100e+07,1545.000000,47.520000,-80.110000,1947.000000,2.018100e+11,12.000000,0.0,99.987790,65.738370,34.285020,49.000000,10.000000,1029.500000,722.000000,2018.000000,0.0,0.0

In [15]:
# Impute missing values using mean imputation for numeric columns
from sklearn.impute import SimpleImputer
numeric_columns = ['Humidity', 'AmbientTemp', 'Wind_Speed', 'Visibility', 'Pressure', 'Cloud.Ceiling']
imputer = SimpleImputer(strategy='mean')
df[numeric_columns] = imputer.fit_transform(df[numeric_columns])

In [16]:
filter = df[(df['Season'] == 'Summer') & (df['Hour'] == 12)]
filter

,Location,Date,Time,Latitude,Longitude,Altitude,YRMODAHRMI,Month,Hour,Season,Humidity,AmbientTemp,PolyPwr,Wind_Speed,Visibility,Pressure,Cloud.Ceiling
437,Camp Murray,20180601,1200,47.11,-122.57,84,2.018060e+11,6,12,Summer,31.98853,22.62024,7.61509,11.0,10.0,1012.6,50.0
441,Camp Murray,20180602,1200,47.11,-122.57,84,2.018060e+11,6,12,Summer,18.26172,37.38403,18.02275,5.0,10.0,1012.6,722.0
446,Camp Murray,20180603,1200,47.11,-122.57,84,2.018060e+11,6,12,Summer,33.02002,28.37822,10.88923,8.0,10.0,1006.2,180.0
453,Camp Murray,20180604,1200,47.11,-122.57,84,2.018060e+11,6,12,Summer,16.74805,36.69922,23.96929,6.0,10.0,1008.2,50.0
466,Camp Murray,20180606,1200,47.11,-122.57,84,2.018060e+11,6,12,Summer,16.81519,40.57648,18.61413,7.0,10.0,1002.9,722.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20873,USAFA,20180827,1215,38.95,-104.83,1947,2.018080e+11,8,12,Summer,16.96777,38.12172,16.77037,14.0,10.0,796.2,722.0
20881,USAFA,20180828,1200,38.95,-104.83,1947,2.018080e+11,8,12,Summer,20.26978,35.42526,15.95123,15.0,10.0,800.9,722.0
20889,USAFA,20180829,1245,38.95,-104.83,1947,2.018080e+11,8,12,Summer,23.27271,38.12172,16.80385,11.0,10.0,802.8,722.0
20895,USAFA,20180830,1200,38.95,-104.83,1947,2.018080e+11,8,12,Summer,13.98926,40.07042,9.23901,11.0,10.0,802.3,722.0
20902,USAFA,20180831,1200,38.95,-104.83,1947,2.018080e+11,8,12,Summer,20.49561,32.89749,9.86962,6.0,10.0,800.3,722.0

In [17]:
value_count = df['Location'].value_counts()
value_count

Travis         2746
Peterson       2640
USAFA          2573
Hill Weber     2384
March AFB      2204
JDMT           1779
Malmstrom      1517
Grissom        1487
Camp Murray    1113
Kahului         941
Offutt          881
MNANG           780
Name: Location, dtype: int64

In [18]:
df['Year'] = df['YRMODAHRMI'] // 100000000
df['Month'] = (df['YRMODAHRMI'] // 1000000) % 100
df['Day'] = (df['YRMODAHRMI'] // 10000) % 100
df['Hour'] = (df['YRMODAHRMI'] // 100) % 100
df['Minute'] = df['YRMODAHRMI'] % 100

df

,Location,Date,Time,Latitude,Longitude,Altitude,YRMODAHRMI,Month,Hour,Season,Humidity,AmbientTemp,PolyPwr,Wind_Speed,Visibility,Pressure,Cloud.Ceiling,Year,Day,Minute
0,Camp Murray,20171203,1145,47.11,-122.57,84,2.017120e+11,12.0,0.0,Winter,81.71997,12.86919,2.42769,5.0,10.0,1010.6,722.0,2017.0,0.0,0.0
1,Camp Murray,20171203,1315,47.11,-122.57,84,2.017120e+11,12.0,0.0,Winter,96.64917,9.66415,2.46273,0.0,10.0,1011.3,23.0,2017.0,0.0,0.0
2,Camp Murray,20171203,1330,47.11,-122.57,84,2.017120e+11,12.0,0.0,Winter,93.61572,15.44983,4.46836,5.0,10.0,1011.6,32.0,2017.0,0.0,0.0
3,Camp Murray,20171204,1230,47.11,-122.57,84,2.017120e+11,12.0,0.0,Winter,77.21558,10.36659,1.65364,5.0,2.0,1024.4,6.0,2017.0,0.0,0.0
4,Camp Murray,20171204,1415,47.11,-122.57,84,2.017120e+11,12.0,0.0,Winter,54.80347,16.85471,6.57939,3.0,3.0,1023.7,9.0,2017.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21040,USAFA,20180928,1530,38.95,-104.83,1947,2.018090e+11,9.0,0.0,Fall,11.66992,43.22510,9.79611,14.0,10.0,802.3,722.0,2018.0,0.0,0.0
21041,USAFA,20180929,1300,38.95,-104.83,1947,2.018090e+11,9.0,0.0,Fall,18.22510,28.98247,10.88992,13.0,10.0,799.2,722.0,2018.0,0.0,0.0
21042,USAFA,20180929,1400,38.95,-104.83,1947,2.018090e+11,9.0,0.0,Fall,15.52124,33.49167,8.24479,10.0,10.0,798.4,722.0,2018.0,0.0,0.0
21043,USAFA,20180929,1500,38.95,-104.83,1947,2.018090e+11,9.0,0.0,Fall,6.63452,51.62163,12.47328,10.0,10.0,797.8,722.0,2018.0,0.0,0.0
21044,USAFA,20181001,1400,38.95,-104.83,1947,2.018100e+11,10.0,0.0,Fall,22.58301,32.83958,6.39732,15.0,10.0,801.2,110.0,2018.0,0.0,0.0

In [19]:
print(df['Year'].min())
print(df['Year'].max())

2017.0
2018.0

In [20]:
value_count = df['Year'].value_counts()
value_count

2018.0    13730
2017.0     7315
Name: Year, dtype: int64

Balance in Dataset

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21045 entries, 0 to 21044
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Location       21045 non-null  object
 1   Date           21045 non-null  int64
 2   Time           21045 non-null  int64
 3   Latitude       21045 non-null  float64
 4   Longitude      21045 non-null  float64
 5   Altitude       21045 non-null  int64
 6   YRMODAHRMI     21045 non-null  float64
 7   Month          21045 non-null  float64
 8   Hour           21045 non-null  float64
 9   Season         21045 non-null  object
 10  Humidity       21045 non-null  float64
 11  AmbientTemp    21045 non-null  float64
 12  PolyPwr        21045 non-null  float64
 13  Wind_Speed     21045 non-null  float64
 14  Visibility     21045 non-null  float64
 15  Pressure       21045 non-null  float64
 16  Cloud.Ceiling  21045 non-null  float64
 17  Year           21045 non-null  float64
 18  Day            21045 non-null  float64
 19  Minute         21045 non-null  float64
dtypes: float64(15), int64(3), object(2)
memory usage: 3.2+ MB

In [22]:
value_count = df['Location'].value_counts()
value_count

Travis         2746
Peterson       2640
USAFA          2573
Hill Weber     2384
March AFB      2204
JDMT           1779
Malmstrom      1517
Grissom        1487
Camp Murray    1113
Kahului         941
Offutt          881
MNANG           780
Name: Location, dtype: int64

In [23]:
value_count = df['Season'].value_counts()
value_count

Summer    8208
Spring    4808
Fall      4407
Winter    3622
Name: Season, dtype: int64

In [24]:
value_count = df['Year'].value_counts()
value_count

2018.0    13730
2017.0     7315
Name: Year, dtype: int64

In [25]:
value_count = df['Month'].value_counts()
value_count

8.0     2935
7.0     2929
6.0     2344
9.0     2244
5.0     1925
4.0     1540
1.0     1382
3.0     1343
11.0    1260
12.0    1137
2.0     1103
10.0     903
Name: Month, dtype: int64

In [26]:
value_count = df['Latitude'].value_counts()
value_count

38.16    2746
38.82    2640
38.95    2573
41.15    2384
33.90    2204
26.98    1779
47.52    1517
40.67    1487
47.11    1113
20.89     941
41.13     881
44.89     780
Name: Latitude, dtype: int64

In [27]:
value_count = df['Longitude'].value_counts()
value_count

-121.56    2746
-104.71    2640
-104.83    2573
-111.99    2384
-117.26    2204
-80.11     1779
-111.18    1517
-86.15     1487
-122.57    1113
-156.44     941
-95.75      881
-93.20      780
Name: Longitude, dtype: int64

In [28]:
value_count = df['Location'].value_counts()
value_count

Travis         2746
Peterson       2640
USAFA          2573
Hill Weber     2384
March AFB      2204
JDMT           1779
Malmstrom      1517
Grissom        1487
Camp Murray    1113
Kahului         941
Offutt          881
MNANG           780
Name: Location, dtype: int64